export const images = [
    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/detail/1", alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/detail/2", alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/detail/3", alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/detail/4", alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/detail/5", alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/detail/6", alt: "Image 6" },
    { url: "/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link: "/detail/7", alt: "Image 7" },
    { url: "/dummy_galleries/zhong-zhou-1.jpg", link: "/detail/8", alt: "Image 8" },

    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/detail/9", alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/detail/10", alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/detail/11", alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/detail/12", alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/detail/13", alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/detail/14", alt: "Image 6" },
    { url: "/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link: "/detail/15", alt: "Image 7" },
    { url: "/dummy_galleries/zhong-zhou-1.jpg", link: "/detail/16", alt: "Image 8" },

    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/detail/9", alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/detail/10", alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/detail/11", alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/detail/12", alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/detail/13", alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/detail/14", alt: "Image 6" },
    { url: "/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link: "/detail/15", alt: "Image 7" },
    { url: "/dummy_galleries/zhong-zhou-1.jpg", link: "/detail/16", alt: "Image 8" },

    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/detail/9", alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/detail/10", alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/detail/11", alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/detail/12", alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/detail/13", alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/detail/14", alt: "Image 6" },
];

export const sliderData = [
    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/artikel/1", title: 'Kompetisi Desain', alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/artikel/2", title: 'Kompetisi Desain', alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/artikel/3", title: 'Kompetisi Desain', alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/artikel/4", title: 'Kompetisi Desain', alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/artikel/5", title: 'Kompetisi Desain', alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/artikel/6", title: 'Kompetisi Desain', alt: "Image 6" },
    { url: "/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link: "/artikel/7", title: 'Kompetisi Desain', alt: "Image 7" },
    { url: "/dummy_galleries/zhong-zhou-1.jpg", link: "/artikel/8", title: 'Kompetisi Desain', alt: "Image 8" },

    { url: "/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link: "/artikel/9", title: 'Kompetisi Desain', alt: "Image 1" },
    { url: "/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link: "/artikel/10", title: 'Kompetisi Desain', alt: "Image 2" },
    { url: "/dummy_galleries/nadya-b-img-2279-min.jpg", link: "/artikel/11", title: 'Kompetisi Desain', alt: "Image 3" },
    { url: "/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link: "/artikel/12", title: 'Kompetisi Desain', alt: "Image 4" },
    { url: "/dummy_galleries/omorphia-visual-gadang.jpg", link: "/artikel/13", title: 'Kompetisi Desain', alt: "Image 5" },
    { url: "/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link: "/artikel/14", title: 'Kompetisi Desain', alt: "Image 6" },
    { url: "/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link: "/artikel/15", title: 'Kompetisi Desain', alt: "Image 7" },
    { url: "/dummy_galleries/zhong-zhou-1.jpg", link: "/artikel/16", title: 'Kompetisi Desain', alt: "Image 8" },
];