export const images = [
    { url: "/resources/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link:"/jelajahi/detail/1", alt: "Image 1" },
    { url: "/resources/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link:"/jelajahi/detail/2", alt: "Image 2" },
    { url: "/resources/dummy_galleries/nadya-b-img-2279-min.jpg", link:"/jelajahi/detail/3", alt: "Image 3" },
    { url: "/resources/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link:"/jelajahi/detail/4", alt: "Image 4" },
    { url: "/resources/dummy_galleries/omorphia-visual-gadang.jpg", link:"/jelajahi/detail/5", alt: "Image 5" },
    { url: "/resources/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link:"/jelajahi/detail/6", alt: "Image 6" },
    { url: "/resources/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link:"/jelajahi/detail/7", alt: "Image 7" },
    { url: "/resources/dummy_galleries/zhong-zhou-1.jpg", link:"/jelajahi/detail/8", alt: "Image 8" },
    { url: "/resources/dummy_galleries/ari-yanto-gatot-kaca-fight-hires-00.jpg", link:"/jelajahi/detail/9", alt: "Image 1" },
    { url: "/resources/dummy_galleries/jonathan-lebrec-rizieres-free.jpg", link:"/jelajahi/detail/10", alt: "Image 2" },
    { url: "/resources/dummy_galleries/nadya-b-img-2279-min.jpg", link:"/jelajahi/detail/11", alt: "Image 3" },
    { url: "/resources/dummy_galleries/oliver-guiney-uncharted-real-redux-03.jpg", link:"/jelajahi/detail/12", alt: "Image 4" },
    { url: "/resources/dummy_galleries/omorphia-visual-gadang.jpg", link:"/jelajahi/detail/13", alt: "Image 5" },
    { url: "/resources/dummy_galleries/tangkas-tahanuji-tongkonan-composed.jpg", link:"/jelajahi/detail/14", alt: "Image 6" },
    { url: "/resources/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link:"/jelajahi/detail/15", alt: "Image 7" },
    { url: "/resources/dummy_galleries/zhong-zhou-1.jpg", link:"/jelajahi/detail/16", alt: "Image 8" },
    { url: "/resources/dummy_galleries/ui_uiiiiiiiii-1-small.jpg", link:"/jelajahi/detail/17", alt: "Image 7" },
    { url: "/resources/dummy_galleries/zhong-zhou-1.jpg", link:"/jelajahi/detail/18", alt: "Image 8" }
];
